### ISSUE TITLE
Touchscreen laptops

### ISSUE THREAD

**Issue by LehtinenRiku** [mjbp/storm-modal#3]
Hi. It seems that toggle doesn't work properly with touchscreen laptops. Only touch opens modal. Not mouse click. Can't provide any more information atm, just what I've heard.

**Comment by mjbp** [comment]
Thanks for reporting this @LehtinenRiku. I'll source a test device and fix in the next day or so.

**Comment by mjbp** [comment]
Version 1.1.6 should address this,  I've added detection/support for pointer events.

Tested on an MS Surface Pro.
